### PR TITLE
Fix proper ability not being imported on creation of custom set

### LINKED ISSUE #265: Abilities on imported sets occasionally reverting to base abilities.
```
Rayquaza-Mega @ Choice Specs  
Ability: Aerilate  
Shiny: Yes  
EVs: 252 HP / 252 Atk / 252 Def / 252 SpA / 252 SpD / 252 Spe  
Modest Nature  
IVs: 0 Atk  
- Boomburst  
- Secret Sword  
- Magma Storm  
- Draco Meteor
```
This set for example, when I import it, the ability sometimes changes to Delta Stream. Do you guys have this same issue? This is particularly annoying when dealing with Balanced Hackmons calcs.

### PR DESCRIPTION
**Pull request by Ntonio36**
Closes #265.

### CODE REVIEW

File: js/moveset_import.js [hunk 1]
```diff
@@ -67,13 +67,12 @@ function serialize(array, separator) {
 }
 
 function getAbility(row) {
-	ability = row[1] ? row[1].trim() : '';
-	if (ABILITIES_SM.indexOf(ability) != -1) {
+	var ability = row[1] ? row[1].trim() : '';
+
```
Comment (AustinXII) [inline js/moveset_import.js]: No space please
